### PR TITLE
fixed packages load problem

### PR DESCRIPTION
**Pull request by beppodotit**
Fixed the packages load problem

The method update_check was taking a long time to complete and repeating it for each brand result in an ajax timeout

### CODE REVIEW

**Comment by tm1000** [comment]
To participate in FreePBX code development you must fill out our CLA: http://wiki.freepbx.org/display/FOP/Code+License+Agreement

**Comment by gherbstman** [comment]
Hi Andrew, Are you trying to suggest something?

**Comment by tm1000** [comment]
I am asking you to fill out the CLA before code can be accepted.

**Comment by beppodotit** [comment]
Ok, I've just sent the form to the address requested in it.

**Comment by beppodotit** [comment]
I don't know why but seems that the change didn't entered in the main code ...

**Comment by tm1000** [comment]
You are right. I just fixed this in 2ad929d

**Pull request merged**
