### PR TITLE
release 14.0.rc

### PR DESCRIPTION
**Pull request by jcattan**
new release for fpbx 14

### CODE REVIEW

**Comment by tm1000** [comment]
1) module.sig should not be included in commits here
2) font awesome should bot be included here (its also missing the font library but thats irrelevant because this already exists in framework anyways)
3) “JC” is not a valid version. Not sure where that came from

**Comment by jcattan** [comment]
ok you can remove the files module.sig and awesome  end you can rename the version in 14.0.0.1 (i add JC for not conflict with your version)

**Comment by matthias1232** [comment]
@jcattan 
you set it as a release candidate, but the Template Manager still does not work with editing files.

If you try to "Edit File Configurations", it only puts you "Texto456" into the text area.
I already try to solve it but cannot find the error at the moment.

**Comment by syadnom** [comment]
@jcattan and @matthias1232  when might this be ready for release?  I'm stuck with the updates.

**Comment by matthias1232** [comment]
@syadnom 
Pull requests are made. We are waiting for merging. Only Sangoma can do this.

**Comment by syadnom** [comment]
@matthias1232 
Do you have a release I could test with? I'm not sure how this is packaged up.

**Comment by matthias1232** [comment]
@syadnom  you can use my fork here:
https://github.com/matthias1232/greenepm

But note:
The Provisioning Package Server is our own server and not FreePBX  mirror by default.
Module is not signed.
Do not use the "experimental" Debug mode, because it is broken.

**Comment by jcattan** [comment]
@syadnom you can use my fork here
https://github.com/jcattan/endpointman/archive/jcattan-jmartin-release-14.0.RC.zip 

it's the Provisioning Package Server of Freepbx
Module is signed
the debug mode woks fine

**Comment by matthias1232** [comment]
@jcattan 
I tested your version but Debug Mode is also broken in your version. Rebuilding of configs does not work with debug mode enabled!
image

**Comment by syadnom** [comment]
I'm not seeing this in SNG7 release.  Isn't the merge from tm1000 supposed make it available?

**Comment by tm1000** [comment]
@syadnom no

**Comment by syadnom** [comment]
probably a good thing.  Fresh install SNG7, installed from the release/14.0 and it breaks when installing yealink modules.

Also not seeing any of the modern Yealinks in the UI despite them being in the files..

**Comment by syadnom** [comment]
...looking in both Yealink V70 and Yealink/Dreamwave.  Not sure what I'm supposed to use there but neither has them.

**Comment by tm1000** [comment]
@syadnom works fine in testing. I don't maintain this module. I just publish it. Sorry.

**Comment by syadnom** [comment]
@tm1000 I did a super basic install.  SNG7 auto install, removed restapps and endpoint manager, installed this module which shows  as v14.0.1.1

literally nothing else touched. 

Whomever tested, did they post any system info on that?  

For instance, I see T4x in the yealinkv70 download, it's in the github repo for it, not in the UI.

**Comment by tm1000** [comment]
> Whomever tested, did they post any system info on that?

I installed the module. That is the extent of testing.

**Comment by syadnom** [comment]
ok, thanks.

@jcattan did you do any testing on the yealink module?  This is the only series of phones I use and this appears to be the only ones broken.  I get a pretty scrambled screen when I install the yealinkv70 so I suspect it's dying while bringing the phones in.  I can see up to T27, so i suppose it's crashing on the t3x or something...

**Comment by jcattan** [comment]
@syadnom you can try to import my package for yealink V80 at http://famillecattan.com/yealinkv80-1525247982.tgz 

@tm1000 the file includes/functions.inc is broken in the version 14.0 there is duplicate of the 60 first lines

**Comment by matthias1232** [comment]
@jcattan @tm1000 
This is already known and pull requests which will fix this are already made.
https://github.com/FreePBX-ContributedModules/endpointman/pull/54
https://github.com/FreePBX-ContributedModules/endpointman/pull/55

**Pull request merged**
